### ISSUE TITLE
Disable The Flashing Dot In Discord For Unread Channels

### ISSUE THREAD

**Issue by JuniorSuperTux** [stronk-dev/Tokyo-Night-Linux#11]
That functionality is really killing my CPU.... Perhaps some instructions on how to disable that?

**Comment by koiosdev** [comment]
Although personally I don't see abnormal CPU usage, I''ll see if I can supply a custom version of the Nocturnal theme.

In the meantime, if you feel up to the task, the theme config (~/.config/BetterDiscord/themes/Nocturnal.theme.css) currently pulls the theme from [here](https://codedotspectra.github.io/themes/themes-cores/nocturnal.css). This file contains all of ze theme code. From a quick glance I can see some `animation:pulse` entries in there, which probably do the flashing dot animations, so modifying that might work.

Let me know if you need any more help, else I will fix this probably some time this weekend 👍

**Comment by Dyzean** [comment]
you can use [this theme](https://github.com/Dyzean/Tokyo-Night) instead if you want

**Comment by stronk-dev** [comment]
Fixed by changing the bundled theme with @Dyzean suggestion!
