### ISSUE TITLE
Make KDE plasma theme

### ISSUE THREAD

**Issue by stronk-dev** [stronk-dev/Tokyo-Night-Linux#13]

**Comment by JuniorSuperTux** [comment]
You can use this one with kvantum. It works pretty well for me.

https://gitlab.com/ObsidianChickenz/kvantum-tokyo-night-theme

**Comment by polnio** [comment]
Sadly the kvantum project seems to be removed, the link points to a 404 page and I don't find any project on ObsidianChickenz's profile. If you have an alternative it's very nice, but in all cases the current link should be removed of README.MD
