### ISSUE TITLE
donations

### ISSUE THREAD

**Issue by sadan4** [stronk-dev/Tokyo-Night-Linux#17]
is there a place to donate?

**Comment by stronk-dev** [comment]
I appreciate it, but it's fine. Repo is not really being maintained anymore (although I'll probably do one last update at some point for the 'final' config - ironically I do most of my work on a Macbook now after customizing my Linux OS to the tits over a span of multiple years 😅).

If you're looking to donate I'd say give it to projects like [oapi-codegen](https://github.com/oapi-codegen/oapi-codegen), FFMPEG, or other open-source projects.
